/* Shangri-La View Hotel — shared Concierge widget
   Loaded by every public/admin page. Dependency-free and isolated in Shadow DOM.
*/
(() => {
  'use strict';
  if (window.__svhConciergeLoaded) return;
  window.__svhConciergeLoaded = true;

  const boot = () => {
    if (!document.body || document.getElementById('svh-concierge-host')) return;
    const host = document.createElement('div');
    host.id = 'svh-concierge-host';
    host.setAttribute('aria-label', 'Shangri-La View Hotel Concierge');
    document.body.appendChild(host);
    const root = host.attachShadow ? host.attachShadow({mode:'open'}) : host;
    const path = location.pathname.toLowerCase();
    const admin = path.includes('admin') || path.includes('login');
    const booking = path.includes('booking');
    const contact = path.includes('contact');
    const gallery = path.includes('gallery');
    root.innerHTML = `
      <style>
        :host{all:initial;position:fixed;right:20px;bottom:20px;z-index:2147483000;font-family:Inter,Arial,sans-serif;color:#f8f2e8}
        *{box-sizing:border-box}.wrap{display:flex;flex-direction:column;align-items:flex-end;gap:12px}.panel{display:none;width:min(370px,calc(100vw - 28px));max-height:min(620px,calc(100vh - 100px));overflow:hidden;flex-direction:column;border:1px solid rgba(199,168,107,.32);border-radius:20px;background:rgba(12,9,10,.97);box-shadow:0 25px 80px rgba(0,0,0,.55);backdrop-filter:blur(18px)}.panel.open{display:flex;animation:up .2s ease}@keyframes up{from{opacity:0;transform:translateY(12px) scale(.98)}to{opacity:1;transform:none}}
        .head{display:flex;align-items:center;gap:11px;padding:15px 16px;background:linear-gradient(135deg,#4f111c,#7f1d2d);border-bottom:1px solid rgba(199,168,107,.2)}.avatar{width:39px;height:39px;display:grid;place-items:center;border:1px solid rgba(224,200,148,.7);border-radius:50%;color:#e0c894;font-family:Georgia,serif;font-size:20px}.head strong{display:block;font-family:Georgia,serif;font-size:16px;font-weight:600}.head small{display:block;margin-top:2px;color:#dfd1bf;font-size:10px}.close{margin-left:auto;width:32px;height:32px;border:0;border-radius:9px;background:rgba(255,255,255,.08);color:#e0c894;font-size:20px;cursor:pointer}
        .messages{display:flex;flex-direction:column;gap:9px;overflow:auto;padding:14px;background:#100b0c;min-height:150px}.msg{max-width:88%;padding:10px 12px;border-radius:13px;font-size:12px;line-height:1.55;white-space:pre-wrap}.bot{align-self:flex-start;background:#1a1113;border:1px solid rgba(199,168,107,.13);color:#eee6db}.user{align-self:flex-end;background:#7f1d2d;color:#fff}.quick{display:flex;gap:7px;overflow:auto;padding:9px 12px 3px;background:#100b0c}.quick button{white-space:nowrap;border:1px solid rgba(199,168,107,.3);border-radius:999px;padding:7px 10px;background:#1a1113;color:#e0c894;font-size:10px;font-weight:600;cursor:pointer}.form{display:flex;gap:7px;padding:10px 12px 12px;border-top:1px solid rgba(199,168,107,.15);background:#120d0e}.input{min-width:0;flex:1;border:1px solid rgba(199,168,107,.25);border-radius:10px;padding:10px 11px;outline:0;background:#090707;color:#f8f2e8;font:inherit;font-size:12px}.input:focus{border-color:#c7a86b;box-shadow:0 0 0 3px rgba(199,168,107,.1)}.send{width:43px;border:0;border-radius:10px;background:#7f1d2d;color:#fff;font-weight:800;cursor:pointer}.send:hover{background:#9a263a}.links{display:flex;gap:7px;padding:0 12px 10px;background:#120d0e}.links a{flex:1;text-align:center;padding:8px;border-radius:9px;background:#1a1113;color:#e0c894;text-decoration:none;font-size:9px;font-weight:700}.launcher{position:relative;width:60px;height:60px;border:1px solid #c7a86b;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#7f1d2d,#4f111c);color:#e0c894;box-shadow:0 15px 40px rgba(0,0,0,.48);cursor:pointer;font-family:Georgia,serif;font-size:25px}.launcher:hover{transform:translateY(-3px)}.badge{position:absolute;right:-1px;top:-2px;width:16px;height:16px;border:2px solid #090707;border-radius:50%;background:#4ade80}.launcher:focus-visible,.close:focus-visible,.quick button:focus-visible,.send:focus-visible{outline:2px solid #e0c894;outline-offset:3px}
        @media(max-width:480px){:host{right:10px;bottom:10px}.panel{width:calc(100vw - 20px)}.launcher{width:55px;height:55px}}
      </style>
      <div class="wrap"><section class="panel" id="panel" aria-hidden="true" aria-label="Hotel Concierge"><div class="head"><div class="avatar">✦</div><div><strong>Shangri-La Concierge</strong><small>Online • ready to assist</small></div><button class="close" id="close" aria-label="Close concierge">×</button></div><div class="messages" id="messages" aria-live="polite"></div><div class="quick" id="quick"></div><div class="links"><a href="booking.html">Book a Room</a><a href="contact.html">Contact</a><a href="https://wa.me/2348030000000" target="_blank" rel="noopener">WhatsApp</a></div><form class="form" id="form"><input class="input" id="input" autocomplete="off" placeholder="Ask about the hotel..." aria-label="Ask the concierge"><button class="send" type="submit" aria-label="Send">➤</button></form></section><button class="launcher" id="launcher" aria-expanded="false" aria-controls="panel" aria-label="Open hotel concierge">✦<span class="badge"></span></button></div>`;
    const $=id=>root.getElementById(id), messages=$('messages'), quick=$('quick'), panel=$('panel');
    const add=(text,who='bot')=>{const el=document.createElement('div');el.className=`msg ${who}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight};
    const reply=q=>{q=q.toLowerCase().trim();if(!q)return 'Tell me what you need help with — rooms, booking, hotel facilities, location, contact details, or your stay.';if(/book|reservation|room|stay|check.?in|check.?out/.test(q))return 'You can make a reservation from our Booking page. Select your preferred room and provide your stay details.';if(/price|rate|cost|how much/.test(q))return 'Room rates can vary by room type and availability. Please open the Booking page or contact the hotel for the current rate.';if(/location|address|where|direction/.test(q))return 'Shangri-La View Hotel is in Port Harcourt, Rivers State, Nigeria. Open Contact for the hotel address and map.';if(/phone|call|contact|email|whatsapp/.test(q))return 'Open the Contact page for the hotel’s contact options, or use the WhatsApp button below.';if(/facility|pool|bar|restaurant|event|hall|service/.test(q))return 'Shangri-La View Hotel offers accommodation and hospitality facilities. Visit the Gallery and About pages to explore the hotel.';if(/gallery|photo|picture/.test(q))return 'Opening the Gallery will let you explore photos of the hotel and its facilities.';if(/admin|manage|dashboard/.test(q))return 'The hotel administration area is protected. Authorized staff can use the Admin page to manage hotel operations.';if(/about|hotel/.test(q))return 'Visit the About page to learn more about Shangri-La View Hotel and its hospitality offering.';return 'I can help with booking, rooms, rates, facilities, directions, contact details, the gallery, and hotel information.'};
    const nav={Booking:'booking.html',Contact:'contact.html',Gallery:'gallery.html',About:'about.html',Admin:'admin.html'};
    const send=t=>{if(!t)return;add(t,'user');const q=t.toLowerCase();if(q.includes('gallery')){setTimeout(()=>{location.href='gallery.html'},220);return}if(q.includes('book')){setTimeout(()=>{location.href='booking.html'},220);return}setTimeout(()=>add(reply(t)),120)};
    const items=admin?['Booking','Contact','Help']:booking?['Rooms','Rates','Contact']:contact?['Booking','Location','WhatsApp']:gallery?['Booking','Contact','About']:['Book a room','Rooms & rates','Contact'];items.forEach(label=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>send(label));quick.appendChild(b)});
    $('form').addEventListener('submit',e=>{e.preventDefault();const i=$('input'),t=i.value.trim();i.value='';send(t)});$('launcher').addEventListener('click',()=>{const open=!panel.classList.contains('open');panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));$('launcher').setAttribute('aria-expanded',String(open));if(open)$('input').focus()});$('close').addEventListener('click',()=>{$('launcher').click()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('open'))$('close').click()});
    add(admin?'Welcome to the hotel concierge. I can help you navigate the hotel site and booking system.':booking?'Welcome. Need help choosing a room or making a reservation?':contact?'Welcome. I can help you find our contact and booking options.':gallery?'Welcome. I can help you explore the hotel and make a reservation.':'Welcome to Shangri-La View Hotel. How may I assist you today?');
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
