/* Shangri-La View Hotel shared Concierge. Safe to load on every page. */
(()=>{
'use strict';
if(window.__svhConciergeLoaded)return;window.__svhConciergeLoaded=true;
const boot=()=>{
 if(!document.body||document.getElementById('svh-concierge-host'))return;
 const host=document.createElement('div');host.id='svh-concierge-host';document.body.appendChild(host);
 const root=host.attachShadow?host.attachShadow({mode:'open'}):host;
 const path=location.pathname.toLowerCase(), admin=/admin|login/.test(path), booking=/booking/.test(path), contact=/contact/.test(path), gallery=/gallery/.test(path);
 root.innerHTML=`<style>
:host{all:initial;position:fixed;right:20px;bottom:20px;z-index:2147483000;font-family:Inter,Arial,sans-serif;color:#f8f2e8}*{box-sizing:border-box}.wrap{display:flex;flex-direction:column;align-items:flex-end;gap:12px}.panel{display:none;width:min(370px,calc(100vw - 28px));max-height:min(620px,calc(100vh - 100px));overflow:hidden;flex-direction:column;border:1px solid #c7a86b55;border-radius:20px;background:#0c090af7;box-shadow:0 25px 80px #0009;backdrop-filter:blur(18px)}.panel.open{display:flex;animation:up .2s ease}@keyframes up{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}.head{display:flex;align-items:center;gap:11px;padding:15px 16px;background:linear-gradient(135deg,#4f111c,#7f1d2d)}.avatar{width:39px;height:39px;display:grid;place-items:center;border:1px solid #e0c894aa;border-radius:50%;color:#e0c894;font:20px Georgia}.head strong{display:block;font:600 16px Georgia}.head small{display:block;margin-top:2px;color:#dfd1bf;font-size:10px}.close{margin-left:auto;width:32px;height:32px;border:0;border-radius:9px;background:#ffffff14;color:#e0c894;font-size:20px;cursor:pointer}.messages{display:flex;flex-direction:column;gap:9px;overflow:auto;padding:14px;background:#100b0c;min-height:150px}.msg{max-width:88%;padding:10px 12px;border-radius:13px;font-size:12px;line-height:1.55;white-space:pre-wrap}.bot{align-self:flex-start;background:#1a1113;border:1px solid #c7a86b22;color:#eee6db}.user{align-self:flex-end;background:#7f1d2d;color:#fff}.quick{display:flex;gap:7px;overflow:auto;padding:9px 12px 3px;background:#100b0c}.quick button{white-space:nowrap;border:1px solid #c7a86b4d;border-radius:999px;padding:7px 10px;background:#1a1113;color:#e0c894;font-size:10px;font-weight:600;cursor:pointer}.form{display:flex;gap:7px;padding:10px 12px 12px;border-top:1px solid #c7a86b26;background:#120d0e}.input{min-width:0;flex:1;border:1px solid #c7a86b40;border-radius:10px;padding:10px 11px;outline:0;background:#090707;color:#f8f2e8;font:12px Inter,Arial}.input:focus{border-color:#c7a86b;box-shadow:0 0 0 3px #c7a86b18}.send{width:43px;border:0;border-radius:10px;background:#7f1d2d;color:#fff;font-weight:800;cursor:pointer}.links{display:flex;gap:7px;padding:0 12px 10px;background:#120d0e}.links a{flex:1;text-align:center;padding:8px;border-radius:9px;background:#1a1113;color:#e0c894;text-decoration:none;font-size:9px;font-weight:700}.launcher{position:relative;width:60px;height:60px;border:1px solid #c7a86b;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#7f1d2d,#4f111c);color:#e0c894;box-shadow:0 15px 40px #0007;cursor:pointer;font:25px Georgia}.badge{position:absolute;right:-1px;top:-2px;width:16px;height:16px;border:2px solid #090707;border-radius:50%;background:#4ade80}@media(max-width:480px){:host{right:10px;bottom:10px}.panel{width:calc(100vw - 20px)}.launcher{width:55px;height:55px}}
</style><div class="wrap"><section class="panel" id="panel" aria-hidden="true"><div class="head"><div class="avatar">✦</div><div><strong>Shangri-La Concierge</strong><small>Online • ready to assist</small></div><button class="close" id="close" aria-label="Close">×</button></div><div class="messages" id="messages" aria-live="polite"></div><div class="quick" id="quick"></div><div class="links"><a href="booking.html">Book a Room</a><a href="contact.html">Contact</a></div><form class="form" id="form"><input class="input" id="input" autocomplete="off" placeholder="Ask about the hotel..." aria-label="Ask the concierge"><button class="send" type="submit">➤</button></form></section><button class="launcher" id="launcher" aria-expanded="false" aria-label="Open hotel concierge">✦<span class="badge"></span></button></div>`;
 const $=id=>root.getElementById(id),panel=$('panel'),messages=$('messages'),quick=$('quick');
 const add=(text,who='bot')=>{const e=document.createElement('div');e.className='msg '+who;e.textContent=text;messages.appendChild(e);messages.scrollTop=messages.scrollHeight};
 const answer=q=>{q=q.toLowerCase().trim();if(!q)return'Tell me what you need help with — rooms, booking, facilities, location, contact details, or your stay.';if(/book|reservation|room|stay|check.?in|check.?out/.test(q))return'You can make a reservation from our Booking page. Select your preferred room and provide your stay details.';if(/price|rate|cost|how much/.test(q))return'Room rates vary by room type and availability. Open the Booking page or contact the hotel for the current rate.';if(/location|address|where|direction/.test(q))return'Shangri-La View Hotel is in Port Harcourt, Rivers State, Nigeria. Open Contact for the hotel address and map.';if(/phone|call|contact|email|whatsapp/.test(q))return'Open the Contact page for the hotel’s current contact options.';if(/facility|pool|bar|restaurant|event|hall|service/.test(q))return'Visit the Gallery and About pages to explore the hotel and its facilities.';if(/gallery|photo|picture/.test(q))return'Visit the Gallery page to explore photos of the hotel and facilities.';if(/admin|manage|dashboard/.test(q))return'The hotel administration area is protected. Authorized staff can use the Admin page.';return'I can help with booking, rooms, rates, facilities, directions, contact details, the gallery, and hotel information.'};
 const send=t=>{if(!t)return;add(t,'user');const q=t.toLowerCase();if(/\bgallery\b/.test(q)){setTimeout(()=>location.href='gallery.html',220);return}if(/\bbook|reservation/.test(q)){setTimeout(()=>location.href='booking.html',220);return}setTimeout(()=>add(answer(t)),120)};
 const items=admin?['Booking','Contact','Help']:booking?['Rooms','Rates','Contact']:contact?['Booking','Location','Help']:gallery?['Booking','Contact','About']:['Book a room','Rooms & rates','Contact'];items.forEach(label=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>send(label);quick.appendChild(b)});
 $('form').onsubmit=e=>{e.preventDefault();const i=$('input'),t=i.value.trim();i.value='';send(t)};$('launcher').onclick=()=>{const open=!panel.classList.contains('open');panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));$('launcher').setAttribute('aria-expanded',String(open));if(open)$('input').focus()};$('close').onclick=()=>$('launcher').click();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('open'))$('close').click()});
 add(admin?'Welcome to the hotel concierge. I can help you navigate the hotel site and booking system.':booking?'Welcome. Need help choosing a room or making a reservation?':contact?'Welcome. I can help you find our contact and booking options.':gallery?'Welcome. I can help you explore the hotel and make a reservation.':'Welcome to Shangri-La View Hotel. How may I assist you today?');
 if(booking && !document.querySelector('script[data-room-video-loader]')){
   const s=document.createElement('script');s.src='booking-room-videos.js';s.defer=true;s.dataset.roomVideoLoader='true';document.head.appendChild(s);
 }
 startLiveDataBridge({admin,booking,contact});
};
const firebaseConfig={apiKey:'AIzaSyDhwIAmuZrY5Xqo6Ql7LDKxrPiklpG5GTE',authDomain:'shangrila-booking.firebaseapp.com',projectId:'shangrila-booking',storageBucket:'shangrila-booking.firebasestorage.app',messagingSenderId:'981170210173',appId:'1:981170210173:web:4d74cb3f6109fe1c0a3814',measurementId:'G-ZYB3J8BW72'};
function loadScript(src){return new Promise((resolve,reject)=>{if(document.querySelector(`script[src="${src}"]`)){resolve();return}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function getDb(){await loadScript('https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore-compat.js');if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);return firebase.firestore()}
function textOf(sel){const el=document.querySelector(sel);return el?el.value.trim():''}
function parseRoom(value){return /^Room\s+(\d+)\s+-\s+(.+?)\s+-\s+₦([\d,]+)/.exec(value||'')}
function escapeHtml(str){return String(str||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function toMillis(v){if(!v)return 0;if(v.toDate)return v.toDate().getTime();if(v.seconds)return v.seconds*1000;const t=new Date(v).getTime();return Number.isNaN(t)?0:t}
function fmt(v){const t=toMillis(v);return t?new Date(t).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}
function statusOf(b){if(b.status==='pending')return['Pending','badge--upcoming'];if(b.status==='cancelled')return['Cancelled','badge--past'];const today=new Date();today.setHours(0,0,0,0);const a=new Date(b.checkIn),z=new Date(b.checkOut);if(!b.checkIn||isNaN(a))return['Unknown','badge--past'];if(today>=a&&(!isNaN(z)&&today<=z))return['Staying','badge--staying'];if(today<a)return['Upcoming','badge--upcoming'];return['Past','badge--past']}
function startLiveDataBridge(ctx){if(ctx.booking)wireBookingForm();if(ctx.admin)setTimeout(enhanceAdmin,400)}
async function wireBookingForm(){const form=document.querySelector('form[action*="formspree.io"]');if(!form||form.dataset.adminBridge)return;form.dataset.adminBridge='true';form.addEventListener('submit',async e=>{e.preventDefault();const room=textOf('#room,[name="room"]'),m=parseRoom(room),checkIn=textOf('#checkin,[name="checkin"]'),checkOut=textOf('#checkout,[name="checkout"]'),name=textOf('#name,[name="name"]'),email=textOf('#email,[name="email"]'),phone=textOf('#phone,[name="phone"]'),message=textOf('#message,[name="message"]');if(!m||!name||!email||!phone||!checkIn||!checkOut||checkOut<=checkIn){form.reportValidity();return}const btn=form.querySelector('button[type="submit"]');const old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='Sending enquiry...'}try{const db=await getDb();const now=firebase.firestore.FieldValue.serverTimestamp();const booking={name,email,phone,room,roomNumber:m[1],roomType:m[2],price:Number(m[3].replace(/,/g,'')),checkIn,checkOut,message,status:'pending',createdAt:now,updatedAt:now};await db.collection('bookings').add(booking);await db.collection('messages').add({name,email,phone,subject:`Booking enquiry for Room ${m[1]}`,message:message||`${name} requested ${room} from ${checkIn} to ${checkOut}.`,source:'Booking form / Formspree',status:'new',roomNumber:m[1],checkIn,checkOut,createdAt:now}).catch(console.warn)}catch(err){console.warn('Admin booking bridge failed:',err)}finally{HTMLFormElement.prototype.submit.call(form);if(btn){btn.disabled=false;btn.textContent=old}}})}
async function enhanceAdmin(){const main=document.querySelector('.main'),sidebar=document.querySelector('.sidebar');if(!main||!sidebar||document.getElementById('svh-live-admin-style'))return;document.head.insertAdjacentHTML('beforeend','<style id="svh-live-admin-style">.svh-message-preview{max-width:360px;white-space:normal;line-height:1.45}.svh-admin-small{display:block;color:var(--ink-muted);font-size:11px;margin-top:4px}.svh-history-list{list-style:none;margin:0;padding:0}.svh-history-list li{display:flex;justify-content:space-between;gap:18px;padding:11px 0;border-bottom:1px solid #EEEAE0;font-size:13px}.svh-history-list li:last-child{border-bottom:0}.svh-history-list .date{font-family:var(--font-mono);font-size:11px;color:var(--ink-muted)}</style>');if(!document.querySelector('[data-view="messages"]')){const link=document.createElement('a');link.className='nav-link';link.dataset.view='messages';link.textContent='✉️ Messages';link.onclick=()=>showView('messages');const guests=document.querySelector('[data-view="guests"]');sidebar.insertBefore(link,guests||null)}if(!document.getElementById('view-messages'))main.insertAdjacentHTML('beforeend','<div class="view" id="view-messages"><h1 class="page-title">Messages</h1><p class="page-sub" id="messageCountLabel">Loading guest messages...</p><div class="table-wrap"><table><thead><tr><th>Guest</th><th>Subject</th><th>Message</th><th>Source</th><th>Date</th><th>Status</th></tr></thead><tbody id="messagesManagementTable"></tbody></table></div></div>');const cards=document.querySelector('.cards');if(cards&&!document.getElementById('statMessages'))cards.insertAdjacentHTML('beforeend','<div class="card"><h3>Messages</h3><p id="statMessages">—</p></div>');const dash=document.getElementById('view-dashboard');if(dash&&!document.getElementById('svhAdminHistory'))dash.insertAdjacentHTML('beforeend','<div class="section" id="svhAdminHistory"><div class="panel"><h3>Recent Messages</h3><table><thead><tr><th>From</th><th>Subject</th><th>Message</th><th>Source</th></tr></thead><tbody id="recentMessagesTable"></tbody></table><div id="recentMessagesEmpty" class="empty-msg" style="display:none;">No messages yet.</div></div><div class="panel"><h3>Activity History</h3><ul class="svh-history-list" id="activityList"></ul><div id="activityEmpty" class="empty-msg" style="display:none;">No activity yet.</div></div></div>');const originalShow=window.showView;window.showView=function(name){if(originalShow)originalShow(name);if(name==='messages')loadAdminMessages()};const originalLoad=window.loadDashboard;window.loadDashboard=async function(){if(originalLoad)await originalLoad();await loadAdminSummary()};await seedDemoHistory();await loadAdminSummary();await loadAdminMessages()}
async function loadAdminCollections(){const db=await getDb();const [b,r,m]=await Promise.all([db.collection('bookings').get(),db.collection('rooms').get(),db.collection('messages').get().catch(()=>({docs:[]}))]);return{bookings:b.docs.map(d=>({id:d.id,...d.data()})),rooms:r.docs.map(d=>({id:d.id,...d.data()})),messages:m.docs.map(d=>({id:d.id,...d.data()}))}}
async function loadAdminSummary(){try{const {bookings,rooms,messages}=await loadAdminCollections();const stat=document.getElementById('statMessages');if(stat)stat.textContent=messages.length;renderRecentMessages(messages);renderActivity(bookings,rooms,messages)}catch(err){console.warn('Admin summary bridge failed:',err)}}
function renderRecentMessages(messages){const body=document.getElementById('recentMessagesTable'),empty=document.getElementById('recentMessagesEmpty');if(!body)return;const rows=[...messages].sort((a,b)=>toMillis(b.createdAt)-toMillis(a.createdAt)).slice(0,5);if(!rows.length){body.innerHTML='';if(empty)empty.style.display='block';return}if(empty)empty.style.display='none';body.innerHTML=rows.map(m=>`<tr><td>${escapeHtml(m.name||'—')}</td><td>${escapeHtml(m.subject||'Guest enquiry')}</td><td class="svh-message-preview">${escapeHtml((m.message||'').slice(0,100))}</td><td>${escapeHtml(m.source||'Website form')}</td></tr>`).join('')}
function renderActivity(bookings,rooms,messages){const list=document.getElementById('activityList'),empty=document.getElementById('activityEmpty');if(!list)return;const items=[...bookings.map(b=>({label:`${b.name||'Guest'} submitted a ${b.status||'pending'} booking for ${b.roomNumber||b.room||'a room'}`,date:b.createdAt||b.updatedAt})),...messages.map(m=>({label:`${m.name||'Guest'} sent a message from ${m.source||'Website form'}`,date:m.createdAt})),...rooms.filter(r=>r.updatedAt).map(r=>({label:`Room ${r.roomNumber||''} updated in admin`,date:r.updatedAt}))].sort((a,b)=>toMillis(b.date)-toMillis(a.date)).slice(0,8);if(!items.length){list.innerHTML='';if(empty)empty.style.display='block';return}if(empty)empty.style.display='none';list.innerHTML=items.map(i=>`<li><span>${escapeHtml(i.label)}</span><span class="date">${escapeHtml(fmt(i.date))}</span></li>`).join('')}
async function loadAdminMessages(){const body=document.getElementById('messagesManagementTable'),label=document.getElementById('messageCountLabel');if(!body)return;try{const db=await getDb();const snap=await db.collection('messages').orderBy('createdAt','desc').get();const rows=snap.docs.map(d=>({id:d.id,...d.data()}));if(label)label.textContent=`${rows.length} guest message${rows.length===1?'':'s'}`;body.innerHTML=rows.length?rows.map(m=>`<tr><td><strong>${escapeHtml(m.name||'—')}</strong><span class="svh-admin-small">${escapeHtml(m.email||'')}<br>${escapeHtml(m.phone||'')}</span></td><td>${escapeHtml(m.subject||'Guest enquiry')}</td><td class="svh-message-preview">${escapeHtml(m.message||'—')}</td><td>${escapeHtml(m.source||'Website form')}</td><td>${escapeHtml(fmt(m.createdAt))}</td><td><span class="badge ${m.status==='handled'?'badge--staying':'badge--upcoming'}">${escapeHtml(m.status||'new')}</span></td></tr>`).join(''):'<tr><td colspan="6" style="text-align:center; padding:40px; color:var(--ink-muted);">No guest messages yet.</td></tr>'}catch(err){console.warn('Could not load messages:',err);if(label)label.textContent='Could not load guest messages.'}}
async function seedDemoHistory(){try{const db=await getDb(),ref=db.collection('settings').doc('demoHistory'),snap=await ref.get();if(snap.exists)return;const ts=s=>firebase.firestore.Timestamp.fromDate(new Date(s));const bookings=[['Adaeze Okonkwo','adaeze.okonkwo@example.com','+234 803 219 4450','Room 204 - Super Deluxe - ₦25,000','204','Super Deluxe',25000,'2026-08-12','2026-08-15','Requested a quiet room and late checkout.','confirmed','2026-08-04T09:45:00+01:00'],['Michael Johnson','michael.johnson@example.com','+234 812 445 9088','Room 309 - Suites - ₦30,000','309','Suites',30000,'2026-08-28','2026-08-31','Anniversary stay. Please prepare the room nicely.','pending','2026-08-20T16:20:00+01:00'],['Chinedu Nwafor','chinedu.nwafor@example.com','+234 909 771 2334','Room 305 - Deluxe - ₦22,000','305','Deluxe',22000,'2026-08-26','2026-08-29','Needs airport pickup information.','confirmed','2026-08-18T14:30:00+01:00']];const messages=[['Grace Williams','grace.williams@example.com','+234 806 441 1029','Event hall enquiry','Hello, do you have availability for a small birthday dinner this weekend?','Website Formspree form','new','2026-08-22T12:05:00+01:00'],['Samuel Eze','samuel.eze@example.com','+234 814 220 7701','Room rate question','Please confirm if the Deluxe room price includes breakfast.','Website contact form','handled','2026-08-19T08:25:00+01:00']];const batch=db.batch();bookings.forEach(x=>batch.set(db.collection('bookings').doc(),{name:x[0],email:x[1],phone:x[2],room:x[3],roomNumber:x[4],roomType:x[5],price:x[6],checkIn:x[7],checkOut:x[8],message:x[9],status:x[10],createdAt:ts(x[11]),updatedAt:ts(x[11]),seeded:true}));messages.forEach(x=>batch.set(db.collection('messages').doc(),{name:x[0],email:x[1],phone:x[2],subject:x[3],message:x[4],source:x[5],status:x[6],createdAt:ts(x[7]),seeded:true}));batch.set(ref,{seededAt:firebase.firestore.FieldValue.serverTimestamp(),note:'Generated starter history for admin dashboard.'});await batch.commit()}catch(err){console.warn('Could not seed demo history:',err)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
